name = "easy-oidc-provider"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
AUTH_URL = "http://localhost:8787"
SITE_NAME = "easy-oidc-provider"

[[d1_databases]]
binding = "DB"
database_name = "easy-oauth-db"
database_id = "8702c798-a252-452d-a8a6-6ad77ccdbc61"
migrations_dir = "migrations"

[triggers]
crons = ["0 3 * * *"]
